### ISSUE TITLE
Revisions to-do

### ISSUE THREAD

**Issue by diazrenata** [diazrenata/birdsize#69]
## Documentation

- [x] reorganize vignettes vs. README. 
- [ ] Make sure vignettes call dependencies properly
- [x] ts
- [ ] make sure AOU is defined
- [x] Clean up plots in vignettes
- [ ] Discuss/deal with uncertainty in estimates
- [x] Make sure normal assumption is stated clearly

## Code

- [x] combine genus and species as scientific_name 993e87f
- [x] consider moving the summarize functions to a vignette
- [x] create brakes around negative body sizes 65ae0fa
    - [x] draw from a truncated normal
    - [x] return a message (not an error) if the parameters supplied would make for a very tiny bird
- [x] move all data documentation to data.R a0a8c9
- [x] rename/rearrange source files
- [x] remove scoped verbs (completed as part of removing tidyverse dependencies) b319ea1 e0cd608
- [x] use NA_character/NA-real a2960ce
- [ ] think about reorganizing nested if statements
- [x] get the R version correct in the DESCRIPTION. Tidyverse depends on R>3.3. _if tidyverse is no longer a dependency, does this still apply?_
- [x] Remove tidyverse dependencies b319ea1 e0cd608
- [x] Remove pipes (*pipes are removed from source code*) 2b24228
- [x] Call package data correctly (not using the assignment operator)
- [x] Move error checking from `ind_draw` to `simulate_populations` 993e87f
- [x] switch AOU to uppercase adc9bd0
- [x] Match test file and source file names
- [ ] Debug unzip issue that is causing a test failure

## Other

- [ ] Consider adding waterbirds and nightbirds
- [x] Message Dunning
